### PR TITLE
Treat ErrorBoundary as a Suspense root in `preact/debug`

### LINKED ISSUE #429: Preact devtools cause async lazy-loaded routes to crash ("Uncaught (in promise) Error: Missing Suspense")
**Describe the bug**

When `import 'preact/debug';` is added at the top of `index.js`, async / lazy components fail to display, the console shows the following error:
```
Uncaught (in promise) Error: Missing Suspense. The throwing component was: 
```

**To Reproduce**

1) `npm init wmr lazy-devtools`
2) `cd lazy-devtools`
3) open `public/index.js`, add `import 'preact/debug';` at the top of the file
4) `npm run start`
5) load `http://192.168.1.127:8080/about` in browser + open web inspector
6) alternatively, load `http://192.168.1.127:8080/` and navigate to `about`

**Expected behavior**

Async lazy-loaded routes do not crash

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - WMR Version: all

Reproduced on Firefox and Chrome with Preact devtools extension version `1.3.0`

**Additional context**

Screenshot 2021-03-14 at 16 58 35

### PR DESCRIPTION
**Pull request by developit**
Fixes #429.

Source reference: https://github.com/preactjs/preact/blob/cd8d65882d08af9f3b7d143d441d128ff068705c/debug/src/debug.js#L57

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]

**Comment by JoviDeCroock** [comment]
Just needs a changeset to go

**Comment by marvinhagemeister** [comment]
We should double check this with devtools in a real world example. Devtools enables additional features for Suspense components like being able to toggle between the fallback and the actual node.

**Comment by developit** [comment]
ahhh interesting @marvinhagemeister - I'm guessing it does that by looking at the internal properties?

**Comment by marvinhagemeister** [comment]
This fix was merged as part of https://github.com/preactjs/wmr/pull/530

**Pull request closed without merging**
