### PR TITLE
Fix sass files not being processed

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fixes the main issue mentioned in #645

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Alright, imo this is ready to be merged.

**Comment by Inviz** [comment]
Great stuff! I think it would be great to test nested imports from sass files (that define variables) and both hmr/build paths for completeness. That's so we can put this sass guy to rest

**Comment by marvinhagemeister** [comment]
@Inviz Agree, the current test suite isn't extensive enough and needs to be enhanced to check for those cases 👍

**Comment by marvinhagemeister** [comment]
Quick update: I think I have now a good overview of the necessary changes to be made to WMR to get this fixed. Whilst this PR fixes the compilation in itself, it doesn't fix HMR issues. For that we need to rework the CSS handling a bit and wire it up into the same plugin-style architecture as we do with the `.js` code.

**Comment by Inviz** [comment]
Thanks Marvin. Yes, that's what I gathered myself, is that it seems that the easy *and* proper fix is out of reach for me and there needs to be a better underlying change for handling css. I think this is a right thing to do and it is very much appreciated

**Pull request closed without merging**
