### PR TITLE
Throw Error when Node doesn't support workers

### PR DESCRIPTION
**Pull request by JoviDeCroock**

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]

**Comment by lukeed** [comment]
`worker_threads.Worker` was added in Node 10.5.0 – https://nodejs.org/api/worker_threads.html#worker_threads_class_worker

Our `engines` protect this from ever happening

**Comment by JoviDeCroock** [comment]
@lukeed Apparently not, @hassanbazzi was running into it with Node 12

**Comment by lukeed** [comment]
Something else going on then. Saw Hassan was using 12.14 – checked that and an older version for good measure.

Screen Shot 2020-12-06 at 12 10 04 PM

**Comment by developit** [comment]
It's likely related to eval inside a Module worker, but I know for sure that works on 12.9+

**Pull request merged**
