### PR TITLE
(wmr) - support tsconfig-paths out of the box

### PR DESCRIPTION
**Pull request by JoviDeCroock**
resolves https://github.com/preactjs/wmr/issues/740

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Currently the netlify build fails because we use `node --experimental-modules` and `tsconfig-paths` only has a CJS export, if we'd use the built wmr version we wouldn't have this issue 😅 it will be that or contributing back an esm export to `tsconfig-paths`.

CC @developit @marvinhagemeister

**Comment by marvinhagemeister** [comment]
Looks like the CI is failing because we're testing against an older Node 12.x release which doesn't include the backported commonjs<->esm interop stuff that newer 12.x releases have. Now with Node 14 being the official LTS I think we're way overdue to update to the newest 12.x release in our pipeline at minimum.

**Comment by JoviDeCroock** [comment]
@marvinhagemeister updated in both netlify and the github workflow

**Review by marvinhagemeister — APPROVED** [review]
Awesome, thanks a bunch 🙌

**Pull request merged**
