### PR TITLE
fixed(router): lazy router flicker

### PR DESCRIPTION
**Pull request by Coiven**
fixed this issue #221

### CODE REVIEW

**Comment by developit** [comment]
hiya - this fix works for synchronous routing, but breaks asynchronous routing.

**Review by developit — CHANGES_REQUESTED** [review]
hiya - this fix works for synchronous routing, but breaks asynchronous routing. I don't know if we have a page in the demo app that would trigger the async case, but it's an important one. I'll try to add a test as a way to clarify.

What we need to do to fix this in a way that accounts for async is to hide the incoming route until it commits.

**Comment by Coiven** [comment]
> What we need to do to fix this in a way that accounts for async is to hide the incoming route until it commits.

yeah, I agree that this is a solution. But I mean that Route Component will always render twice when route changes. Is it better to wait for the incoming route to be ready before returning than show/hide.

**Comment by developit** [comment]
@Coiven components can't wait/defer.

**Comment by danielweck** [comment]
I believe this was fixed via https://github.com/preactjs/wmr/pull/337
Can this PR now be closed?

**Pull request closed without merging**
