### PR TITLE
(wmr) - use swc to minify code

### PR DESCRIPTION
**Pull request by JoviDeCroock**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you try last version of swc?
Rules are not implemented yet, but now it generates much compact code.

**Comment by JoviDeCroock** [comment]
Bumped it to latest

**Comment by kdy1** [comment]
Seems like I made a mistake. I'll investigate

**Comment by marvinhagemeister** [comment]
FYI: Managed to trim down the CI inifinite loop error to a minimal repro. See: https://github.com/swc-project/swc/issues/2044

**Comment by marvinhagemeister** [comment]
The CI failure is caused by an upstream bug in `swc`'s minifier in regards to mangling variables and shorthand properties. Reported it here: https://github.com/swc-project/swc/issues/2051

**Comment by marvinhagemeister** [comment]
FYI: Tests are failing due to a minification bug in swc: https://github.com/swc-project/swc/issues/2078

**Comment by marvinhagemeister** [comment]
@JoviDeCroock looks like we'd only need to update the assertion to check for double quotes in the two failing tests 🎉

**Comment by kdy1** [comment]
@JoviDeCroock Is there a reason you closed this?

**Comment by JoviDeCroock** [comment]
@kdy1 well if I understood correctly the emphasis of swc has moved to being Rust-based for plugins and we don't currently have any Rust in wmr (and I don't know how that boats with my fellow contributors). I've closed this as I'm investigating what is causing the build to fail and want to isolate the bugs.

**Comment by kdy1** [comment]
Minifier is not affected by plugin api. Plugin api only applies to `transform` apis.
Maybe https://github.com/swc-project/swc/issues/2262 can be the cause.

**Comment by JoviDeCroock** [comment]
Currently seeing:

```
12:01:52 PM: The following error was thrown during prerendering:
12:01:52 PM: SyntaxError: Missing initializer in const declaration
12:01:52 PM: 
12:01:52 PM:     at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
12:01:52 PM:     at async link (internal/modules/esm/module_job.js:37:21)
12:01:52 PM: /bin/sh: 1: wmr: not found
12:01:52 PM: error Command failed with exit code 127.
```

For the docs site, I'll look into it later

**Comment by kdy1** [comment]
Seems like the minifier tries to inline or drop the initializer of the variable, but didn't remove the variable itself.
I'll try fixing some known issues of the minifier.

**Comment by fabiosantoscode** [comment]
Love this ❤️

**Pull request closed without merging**
