### PR TITLE
chore: purge unused plugins

### PR DESCRIPTION
**Pull request by lukeed**
I hate to do it, but these two have no references anywhere. There's a lot going on the repo so might be best to trim away the unnecessary bits.

There's also the `unpkg` plugin (and one other, but I forget) that has a commented-out import. I left those.

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]
Good spot!

**Comment by developit** [comment]
Good catch on the watcher plugin. The dynamic import names I actually think we might need - I don't know why it wasn't being used...

**Comment by lukeed** [comment]
Should I revert that file?

**Comment by developit** [comment]
For now that's probably best - we can delete it once we've confirmed, but it wasn't supposed to be dead code :P

**Comment by lukeed** [comment]
Restored via force push

**Review by developit — APPROVED** [review]
LGTM

**Pull request merged**
